---
# tasks/main.yml: "Master" playbook for the cmacrae.sensu role

  - include_vars: "{{ ansible_distribution }}.yml"
    when: windows_server != "yes"

  - include_vars: "{{ ansible_os_family }}.yml"
    when: windows_server == "yes"

  - include: "{{ role_path }}/tasks/{{ ansible_distribution }}/main.yml"
    tags: setup
    when: windows_server != "yes"

    # windows server path with no spaces
  - include: "{{ role_path }}/tasks/{{ ansible_os_family }}/main.yml"
    tags: setup
    when: windows_server == "yes"

  - include: "{{ role_path }}/tasks/pdagent.yml"
    tags: pdagent
    when: pdagent

  - include: "{{ role_path }}/tasks/redis.yml"
    tags: redis
    when: redis_server
          and sensu_deploy_redis
    static: false

  - include: "{{ role_path }}/tasks/ssl.yml"
    tags: ssl
    when: windows_server != "yes"

  - include: "{{ role_path }}/tasks/rabbit.yml"
    tags: rabbitmq
    when: rabbitmq_server
          and sensu_deploy_rabbitmq
    static: false
    when: windows_server != "yes"

  - include: "{{ role_path }}/tasks/common.yml"
    tags: common
    when: windows_server != "yes"

  - include: "{{ role_path }}/tasks/server.yml"
    tags: server
    when: sensu_master
    static: false

  - include: "{{ role_path }}/tasks/dashboard.yml"
    tags: dashboard
    when: sensu_include_dashboard
    static: false

  - include: "{{ role_path }}/tasks/client.yml"
    tags: client
    when: windows_server != "yes"

  - include: "{{ role_path }}/tasks/windows_client.yml"
    tags: client
    when: windows_server == "yes"

  - include: "{{ role_path }}/tasks/plugins.yml"
    tags: plugins
    when: sensu_include_plugins
          and windows_server != "yes"
    static: false
