---
# tasks/Ubuntu/rabbit.yml: Deploy RabbitMQ
# Specific to Ubuntu

  - include_vars: "{{ ansible_distribution }}.yml"

  # https://www.rabbitmq.com/signatures.html
  - name: Ensure the PackageCloud APT repo GPG key is present
    apt_key:
      url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
      state: present

  - name: Ensure the RabbitMQ APT repo GPG key is present
    apt_key:
      url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
      state: present

  # https://www.rabbitmq.com/install-debian.html
  - name: Ensure the RabbitMQ APT repo is present
    apt_repository:
      repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_distribution_release }} main"
      filename: rabbitmq
      state: present
      update_cache: true

  - name: Ensure the Erlang APT repo GPG key is present
    apt_key:
      url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      state: present

  - name: Ensure the Erlang APT repo is present
    apt_repository:
      repo: "deb https://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release }} contrib"
      filename: erlang
      state: present
      update_cache: true

  - name: Force remove RabbitMQ
    shell: apt-get purge -y --allow-change-held-packages rabbitmq-server
    args:
      warn: false

  - name: Ensure RabbitMQ is installed
    apt:
      name: rabbitmq-server=3.9.23-1
      #allow_downgrade: true
      state: "{{ rabbitmq_pkg_state }}"
      cache_valid_time: 600
      update_cache: true

  - name: Mark packages selection state to hold
    dpkg_selections:
      name: "rabbitmq-server"
      selection: hold
